<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-08-09T09:20:30+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      http_client.sslverifypeer
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'http_client' => [
        'sslverifypeer' => false,
    ],
];
