<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-05-22T16:05:53+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.editor.ckeditor4.plugins.selected
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Chris Watterston',
            'editor' => [
                'concrete' => [
                    'enable_filemanager' => '1',
                    'enable_sitemap' => '1',
                ],
                'ckeditor4' => [
                    'plugins' => [
                        'selected' => [
                            'concrete5filemanager',
                            'concrete5inline',
                            'concrete5uploadimage',
                            'dialogadvtab',
                            'divarea',
                            'floatingspace',
                            'normalizeonchange',
                            'resize',
                            'toolbar',
                            'wysiwygarea',
                            'elementspath',
                            'entities',
                            'format',
                            'htmlwriter',
                            'image',
                            'indentblock',
                            'indentlist',
                            'list',
                            'liststyle',
                            'removeformat',
                            'showblocks',
                            'sourcearea',
                            'sourcedialog',
                            'table',
                            'concrete5link',
                            'concrete5styles',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
