<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-05-11T11:48:40+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      paypalCurrency
 * @group     vividstore
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'symbol' => '£',
    'whole' => '.',
    'thousand' => ',',
    'taxenabled' => null,
    'taxcountry' => null,
    'taxstate' => null,
    'taxcity' => '',
    'taxAddress' => '',
    'taxMatch' => '',
    'taxBased' => '',
    'taxrate' => '',
    'taxName' => '',
    'calculation' => 'add',
    'shippingenabled' => null,
    'shippingbase' => null,
    'shippingitem' => null,
    'weightUnit' => 'g',
    'sizeUnit' => 'mm',
    'notificationemails' => 'hello@chriswatterston.com',
    'emailalerts' => 'hello@chriswatterston.com',
    'productPublishTarget' => '0',
    'guestCheckout' => 'always',
    'authnetLoginID' => '',
    'authnetTransactionKey' => '',
    'authnetTestmode' => '0',
    'invoiceMinimum' => '',
    'invoiceMaximum' => '',
    'paypalEmail' => 'chris@chriswatterston.com',
    'paypalTestMode' => '0',
    'paypalCurrency' => 'GBP',
);
